version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: muhammad-abid-portfolio
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
    volumes:
      # Persist logs
      - ./logs/nginx:/var/log/nginx
      - ./logs/supervisor:/var/log/supervisor
      # Persist contact form logs
      - ./logs/api:/var/www/html/api/logs
    networks:
      - portfolio_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  portfolio_network:
    driver: bridge

volumes:
  logs:

